### ISSUE TITLE
每次都初始化一个新的stack，性能自然不会太好

### ISSUE THREAD

**Issue by keiaos** [Peefy/StackMachine#1]
https://github.com/Peefy/StackMachine/blob/ef6a892d33d984eac18a932a68c3168bc1592b8f/src/main.py#L81

**Comment by Peefy** [comment]
> https://github.com/Peefy/StackMachine/blob/ef6a892d33d984eac18a932a68c3168bc1592b8f/src/main.py#L81

感谢反馈，感觉这里是一个 Stack list 引用哈，如有不对，请指出。

**Comment by keiaos** [comment]
self.stack[:len(self.stack)-1]  -- 这里每次都重新生成一个新的stack

**Comment by Peefy** [comment]
> self.stack[:len(self.stack)-1] -- 这里每次都重新生成一个新的stack

好，感谢反馈，我会将该处 stack 的浅拷贝进行优化进行一定的性能提升，stack 中的 KCLObject 仍然是引用的拷贝
